resilience4j:
  circuitbreaker:
   backends:
     default:
      #slidingWindowSize: 10   #number of calls to consider failure threshold
      failureRateThreshold: 100   #  number of calls failed/slidingwindow size
      waitDurationInOpenState: 30s  # wait 30s 
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      minimumNumberOfCalls: 10
  retry:
    backends:
      default:
        max-retry-attempts: 5
        #wait-duration: 100
      
    
    

#STATE: CLOSED; 9 exceptions must be triggered in order to switch from CLOSED -> OPEN (because failureRateThreshold = 100%)
#STATE: OPEN; after 30seconds the state is automatically changed from OPEN -> HALF_OPEN
#STATE: HALF_OPEN; at least 5 calls needed to change from HALF_OPEN -> OPEN (if fails) or HALF_OPEN -> CLOSED (if succeeds). [IMPORTANT: 100% out 3 calls should fail in order to change from HALF_OPEN -> OPEN]


